# Generated by Django 3.2 on 2021-05-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0009_auto_20210503_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepc',
            name='id_manuf',
            field=models.ForeignKey(db_column='Id_manuf', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooler',
            name='id_manuf',
            field=models.ForeignKey(db_column='Id_manuf', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ddr',
            name='id_manuf',
            field=models.ForeignKey(db_column='Id_manuf', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hdd',
            name='id_manuf',
            field=models.ForeignKey(db_column='Id_manuf', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboard',
            name='id_manuf',
            field=models.ForeignKey(db_column='Id_manuf',  on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powersupply',
            name='id_manuf',
            field=models.ForeignKey(db_column='Id_manuf',  on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processor',
            name='id_manuf',
            field=models.ForeignKey(db_column='Id_manuf',  on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssd',
            name='id_manuf',
            field=models.ForeignKey(db_column='Id_manuf',  on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocard',
            name='id_manuf',
            field=models.ForeignKey(db_column='Id_manuf', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.manufacturer'),
            preserve_default=False,
        ),
    ]
