# Generated by Django 3.2 on 2021-05-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_auto_20210516_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ddr',
            old_name='ddr_rub',
            new_name='price_rub',
        ),
        migrations.AlterField(
            model_name='pcassembly',
            name='id_case',
            field=models.ForeignKey(db_column='Id_case', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.casepc', verbose_name='Наименовение корпуса'),
        ),
        migrations.AlterField(
            model_name='pcassembly',
            name='id_cooler',
            field=models.ForeignKey(db_column='Id_cooler', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.cooler', verbose_name='Наименовение кулера'),
        ),
        migrations.AlterField(
            model_name='pcassembly',
            name='id_motherboard',
            field=models.ForeignKey(db_column='Id_Motherboard', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.motherboard', verbose_name='Наименование мат. платы'),
        ),
        migrations.AlterField(
            model_name='pcassembly',
            name='id_power_supply',
            field=models.ForeignKey(db_column='Id_power_supply', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.powersupply', verbose_name='Наименование блока питания'),
        ),
        migrations.AlterField(
            model_name='pcassembly',
            name='id_proc',
            field=models.ForeignKey(db_column='Id_proc', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.processor', verbose_name='Наименование процессора'),
        ),
        migrations.AlterField(
            model_name='pcassembly',
            name='id_storage',
            field=models.ManyToManyField(db_column='Id_storage', related_name='PcAssemblyies', to='assembly.Storage', verbose_name='Наименование накопителя'),
        ),
        migrations.AlterField(
            model_name='pcassembly',
            name='id_user',
            field=models.ForeignKey(db_column='Id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.authuser', verbose_name='ФИО пользователя'),
        ),
        migrations.AlterField(
            model_name='pcassembly',
            name='id_vga',
            field=models.ForeignKey(db_column='Id_vga', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.videocard', verbose_name='Наименование видеокарты'),
        ),
        migrations.AlterField(
            model_name='pcassembly',
            name='pc_assembly_date',
            field=models.DateTimeField(db_column='Pc_assembly_date', verbose_name='Дата/время'),
        ),
        migrations.AlterField(
            model_name='pcassembly',
            name='pc_assembly_price_end',
            field=models.IntegerField(db_column='Pc_assembly_price_end', verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='id_manuf',
            field=models.ForeignKey(db_column='Id_manuf', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='power_supply_power',
            field=models.IntegerField(db_column='Power_supply_ power', verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='tdp',
            field=models.IntegerField(db_column='TDP', verbose_name='Тепловыделение(TDP)'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='id_type_mem',
            field=models.ForeignKey(db_column='Id_type_mem_', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.typememory', verbose_name='Тип видеопамяти'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='memory_frequency',
            field=models.IntegerField(db_column='Memory_frequency', verbose_name='Частота видеопамяти'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='video_frequency',
            field=models.IntegerField(db_column='Video_frequency', verbose_name='Частота графического процессора'),
        ),
    ]
