# Generated by Django 3.2 on 2021-05-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_auto_20210519_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_param_ddr',
            field=models.CharField(db_column='Answer_param_ddr', default=4, max_length=255, verbose_name='Необходимый объем опер. памяти'),
        ),
    ]
