# Generated by Django 3.2 on 2021-06-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0006_result_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='cooler',
            field=models.CharField(db_column='Cooler', max_length=255, verbose_name='Кулер'),
        ),
        migrations.AlterField(
            model_name='result',
            name='ddr',
            field=models.CharField(db_column='DDR', max_length=255, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id_pc_assembly',
            field=models.ForeignKey(db_column='Id_Pc_assembly', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.pcassembly', verbose_name='Сборка'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id_test',
            field=models.ForeignKey(db_column='Id_test', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='result',
            name='mboard',
            field=models.CharField(db_column='Mboard', max_length=255, verbose_name='Мат. плата'),
        ),
        migrations.AlterField(
            model_name='result',
            name='power_supply',
            field=models.CharField(db_column='Power_supply', max_length=255, verbose_name='Блок питания'),
        ),
        migrations.AlterField(
            model_name='result',
            name='proc',
            field=models.CharField(db_column='Proc', max_length=255, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_date',
            field=models.DateTimeField(db_column='Result_date', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_price_end',
            field=models.IntegerField(db_column='Result_price_end', verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_title',
            field=models.CharField(db_column='Result_title', max_length=255, verbose_name='Наименование сохраненной сборки'),
        ),
        migrations.AlterField(
            model_name='result',
            name='storage',
            field=models.CharField(db_column='Storage', max_length=255, verbose_name='Накопитель'),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(db_column='Id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.authuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='result',
            name='video',
            field=models.CharField(db_column='Video', max_length=255, verbose_name='Видеокарта'),
        ),
    ]
