# Generated by Django 3.2 on 2021-06-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0007_auto_20210609_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='case',
            field=models.CharField(db_column='CasePC', default=1, max_length=255, verbose_name='Наименовение корпуса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pcassembly',
            name='id_ddr',
            field=models.ForeignKey(db_column='Id_ddr', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.ddr', verbose_name='Наименование оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='pcassembly',
            name='pc_assembly_date',
            field=models.DateTimeField(db_column='Pc_assembly_date', verbose_name='Дата/время создания'),
        ),
        migrations.AlterField(
            model_name='result',
            name='cooler',
            field=models.CharField(db_column='Cooler', max_length=255, verbose_name='Наименовение кулера'),
        ),
        migrations.AlterField(
            model_name='result',
            name='ddr',
            field=models.CharField(db_column='DDR', max_length=255, verbose_name='Наименование оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id_pc_assembly',
            field=models.ForeignKey(db_column='Id_Pc_assembly', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.pcassembly', verbose_name='Наименование сборки'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id_test',
            field=models.ForeignKey(db_column='Id_test', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.test', verbose_name='Наименование теста'),
        ),
        migrations.AlterField(
            model_name='result',
            name='mboard',
            field=models.CharField(db_column='Mboard', max_length=255, verbose_name='Наименование мат. платы'),
        ),
        migrations.AlterField(
            model_name='result',
            name='power_supply',
            field=models.CharField(db_column='Power_supply', max_length=255, verbose_name='Наименование блока питания'),
        ),
        migrations.AlterField(
            model_name='result',
            name='proc',
            field=models.CharField(db_column='Proc', max_length=255, verbose_name='Наименование процессора'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_date',
            field=models.DateTimeField(db_column='Result_date', verbose_name='Дата/время создания'),
        ),
        migrations.AlterField(
            model_name='result',
            name='storage',
            field=models.CharField(db_column='Storage', max_length=255, verbose_name='Наименование накопителя'),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(db_column='Id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='assembly.authuser', verbose_name='ФИО пользователя'),
        ),
        migrations.AlterField(
            model_name='result',
            name='video',
            field=models.CharField(db_column='Video', max_length=255, verbose_name='Наименование видеокарты'),
        ),
    ]
