# Generated by Django 3.2 on 2021-06-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0008_auto_20210609_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fb_date',
            field=models.DateTimeField(db_column='FB_date',  verbose_name='Дата/время создания'),
            preserve_default=False,
        ),
    ]
