# Generated by Django 3.2 on 2021-06-14 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0009_feedback_fb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fb_date',
            field=models.DateTimeField(db_column='FB_date', default=datetime.datetime.now, verbose_name='Дата/время создания'),
        ),
    ]
